[project]
name = "repo-perso-school-extrem2026"
version = "0.1.0"
description = "Demo extrem"
authors = [
    {name = "Pierre Augier", email = "p.a@uga.fr"},
]
dependencies = []
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
